version: "3.8"
services:
  mysqldb:
    image: mysql
    container_name: db
    restart: on-failure
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: deluxeperfumes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - deluxeperfumes-network
  deluxeperfumes-app:
    hostname: backend
    restart: on-failure
    depends_on:
      - mysqldb
    links:
      - mysqldb
    image: deluxeperfumes-app
    container_name: deluxeperfumes-container
    build: deluxeperfumes-service
    ports:
      - "8080:8080"
    networks:
      - deluxeperfumes-network

networks:
  deluxeperfumes-network: